name: example
description: A new Flutter package project.
version: 0.0.1
homepage: none
publish_to: none


environment:
  sdk: ">=2.11.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get_storage: ^2.0.3
  q_ratio:
    path: ../
  get: ^4.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
  - assets/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf
          style: normal
          weight: 900
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
          style: normal
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
          style: normal
          weight: 500
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
          style: normal
          weight: 300
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          style: normal
          weight: 200
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Thin.ttf
          style: normal
          weight: 100