name: q_ratio
description: Q ratio, a simple ratio calculator.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.3.8

  bootstrap:
    git:
      url: https://gitlab.com/salario/bootstrap.git
      ref: master
  get_storage: ^2.0.3

  cupertino_icons: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
